stingus_jira_connect:
    path:     /_jira/connect/{consumerKey}/{baseUrl}
    defaults: { _controller: StingusJiraBundle:Oauth:connect }

stingus_jira_callback:
    path:     /_jira/callback
    defaults: { _controller: StingusJiraBundle:Oauth:callback }
